### ISSUE TITLE
Error when run "jedi" after install.

### ISSUE THREAD

**Issue by Tanato** [jediproject/generator-jedi#5]
After installing generator-jedi, we have a issue when running jedi to start the web wizard.

The error:

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tanato\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.5.3

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\tanato\AppData\Roaming\npm\node_modules\generator-jedi\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tanato\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "develop"
npm ERR! node v4.2.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! generator-jedi@0.0.9 develop: `npm install && bash gui/run.sh develop && node gui/server/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the generator-jedi@0.0.9 develop script 'npm install && bash gui/run.sh develop && node gui/server/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the generator-jedi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && bash gui/run.sh develop && node gui/server/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs generator-jedi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls generator-jedi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\tanato\AppData\Roaming\npm\node_modules\generator-jedi\npm-debug.log
```
- npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\tanato\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'develop' ]
2 info using npm@3.5.3
3 info using node@v4.2.1
4 verbose run-script [ 'predevelop', 'develop', 'postdevelop' ]
5 info lifecycle generator-jedi@0.0.9~predevelop: generator-jedi@0.0.9
6 silly lifecycle generator-jedi@0.0.9~predevelop: no script for predevelop, continuing
7 info lifecycle generator-jedi@0.0.9~develop: generator-jedi@0.0.9
8 verbose lifecycle generator-jedi@0.0.9~develop: unsafe-perm in lifecycle true
9 verbose lifecycle generator-jedi@0.0.9~develop: PATH: C:\Users\tanato\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\tanato\AppData\Roaming\npm\node_modules\generator-jedi\node_modules\.bin;C:\Users\tanato\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\cmder\vendor\conemu-maximus5;C:\Program Files (x86)\cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\oracle\product\10.2.0\client_1\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Perforce;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Perforce\DVCS\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\tanato\AppData\Roaming\npm;C:\Users\tanato\AppData\Local\Programs\Git\cmd;C:\Program Files (x86)\Git\libexec\git-core
10 verbose lifecycle generator-jedi@0.0.9~develop: CWD: C:\Users\tanato\AppData\Roaming\npm\node_modules\generator-jedi
11 silly lifecycle generator-jedi@0.0.9~develop: Args: [ '/d /s /c',
11 silly lifecycle   'npm install && bash gui/run.sh develop && node gui/server/app.js' ]
12 silly lifecycle generator-jedi@0.0.9~develop: Returned: code: 1  signal: null
13 info lifecycle generator-jedi@0.0.9~develop: Failed to exec develop script
14 verbose stack Error: generator-jedi@0.0.9 develop: `npm install && bash gui/run.sh develop && node gui/server/app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\tanato\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\tanato\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid generator-jedi@0.0.9
16 verbose cwd C:\Users\tanato\AppData\Roaming\npm\node_modules\generator-jedi
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tanato\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "develop"
19 error node v4.2.1
20 error npm  v3.5.3
21 error code ELIFECYCLE
22 error generator-jedi@0.0.9 develop: `npm install && bash gui/run.sh develop && node gui/server/app.js`
22 error Exit status 1
23 error Failed at the generator-jedi@0.0.9 develop script 'npm install && bash gui/run.sh develop && node gui/server/app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the generator-jedi package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm install && bash gui/run.sh develop && node gui/server/app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs generator-jedi
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls generator-jedi
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by Tanato** [comment]
This issue is not in generator, it's in npm install command and it's related to a network problem, reported in issue npm/npm#7862

I'll try to fix it by creating an script that runs separately every dependency

**Comment by hsbrighenti** [comment]
Similar: npm/npm#10686

**Comment by fabioviana** [comment]
I solve this problem adding the assets files on the repo.
